### PR TITLE
Check commits

### PR DESCRIPTION
**Pull request by rjarry**

### CODE REVIEW

**Review by samuel-gauthier — COMMENTED** [review]
Shouldn't we mention this in the project README? Otherwise, looks good to me.

**Comment by rjarry** [comment]
Good point. I will update the readme with the commit message rules.

**Comment by rjarry** [comment]
I have made the same changes as here: https://github.com/sysrepo/sysrepo-python/pull/64

**Review by samuel-gauthier — APPROVED** [review]

**Comment by samuel-gauthier** [comment]
Approved!

**Pull request merged**
