### PR TITLE
Feature/builtin plugins only

### PR DESCRIPTION
**Pull request by steweg**

### CODE REVIEW

**Comment by rjarry** [comment]
Hi,

libyang-python only supports the master branch of C libyang (currently 2.x).

The lydevel check is only meant for informative purposes.

https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20

If it fails (currently it should fail because libyang 3.x is under development) it is not a problem. 

Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?

Thank you.

**Review by rjarry — CHANGES_REQUESTED** [review]
Hi,

libyang-python only supports the master branch of C libyang (currently 2.x).

The lydevel check is only meant for informative purposes.

https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20

If it fails (currently it should fail because libyang 3.x is under development) it is not a problem. 

Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?

Thank you.

**Comment by steweg** [comment]
> Hi,
> 
> libyang-python only supports the master branch of C libyang (currently 2.x).
> 
> The lydevel check is only meant for informative purposes.
> 
> https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20
> 
> If it fails (currently it should fail because libyang 3.x is under development) it is not a problem.
> 
> Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?
> 
> Thank you.

Unfortunately again, this feature requires to use `libyang 3.0.X`, so this has to wait. I will separate just the bug-fix commit, which is valid even for `libyang 2.X.X` and create separate PR for that

**Comment by samuel-gauthier** [comment]
It tried the first commit and it does not seem to work (the unit test gives me a validation error). If you still want this integrated, could you rebase and recheck? Also, why do we need the last commit for, as it not seem related to the two others?

**Comment by steweg** [comment]
Rebased as requested

**Comment by samuel-gauthier** [comment]
Also, why do we need the last commit, as it does not seem related to the two others?
Is it because of the previous changes? Can you explain in more detail, I don't understand why we need it.

**Comment by steweg** [comment]
It is indirectly related. The thing is that once you want to use feature like using of built in plugins only and store only, then you are able to create dnode which passes only very basic checks (like that value is a string type) but slipping the advanced checks (like matching regexps etc.). This works nicely but then when you want to print the data, it will fail as the current printing of value procedure is also performing value validation against full set of check, which is totally unexpected behavior from end-user perspective.

**Comment by steweg** [comment]
> I found the time to fix the last commit, which could sometimes stay forever in the while loop.

Are you sure this works even for "union of union of union..." and also for "leafref pointing to another leafref, pointing to another leafref.."?

Also I cannot really imagine a valid YANG schema, which will trigger infinite loop. Only "looped" YANG schema can do that, which shall not even pass through schema validation in general. If it does, then there is a bug in libyang schema validation code and shall be fixed rather there, not in this function.... Can you give me an example of such schema?

**Comment by samuel-gauthier** [comment]
With the code from your commit, our internal tests were looping.
The committed code is similar to what is done in lyd_value_validate, without the validation part, which does what you requested. And it works the same as before, as lyd_value_validate was called before.
Let's reopen this discussion in another issue if you find a problem.

**Pull request closed without merging**
