### PR TITLE
Feature/leafref linking

### PR DESCRIPTION
**Pull request by steweg**

### CODE REVIEW

**Comment by rjarry** [comment]
Hi,

libyang-python only supports the master branch of C libyang (currently 2.x).

The lydevel check is only meant for informative purposes.

https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20

If it fails (currently it should fail because libyang 3.x is under development) it is not a problem. 

Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?

Thank you.

**Review by rjarry — CHANGES_REQUESTED** [review]
Hi,

libyang-python only supports the master branch of C libyang (currently 2.x).

The lydevel check is only meant for informative purposes.

https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20

If it fails (currently it should fail because libyang 3.x is under development) it is not a problem. 

Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?

Thank you.

**Comment by steweg** [comment]
> Hi,
> 
> libyang-python only supports the master branch of C libyang (currently 2.x).
> 
> The lydevel check is only meant for informative purposes.
> 
> https://github.com/CESNET/libyang-python/blob/f09ed1164d860fd9f04c008e42bbac13ccdb2ff2/tox.ini#L18-L20
> 
> If it fails (currently it should fail because libyang 3.x is under development) it is not a problem.
> 
> Could you remove all references to libyang 3 which was not released yet and only focus on the enhancements that you require?
> 
> Thank you.

This feature is actually requires usage of `libyang 3.0.X`, so this needs to wait till then.

**Comment by samuel-gauthier** [comment]
Pushed with minor changes.

**Pull request closed without merging**
